version: "3.8"
services:
  redisreft01:
    image: bootjp/redis_raft:latest
    ports:
      - "5001:5001"
    networks:
      - nodes
    environment:
      - PORT=5001
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  redisreft02:
    image: bootjp/redis_raft:latest
    ports:
      - "5002:5001"
    networks:
      - nodes
    environment:
      - PORT=5002
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  redisreft03:
    image: bootjp/redis_raft:latest
    ports:
      - "5003:5001"
    networks:
      - nodes
    environment:
      - PORT=5003
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

networks:
  nodes:

